output: /benchmark
vis: 0
# num_workers: 4        # Defaults to os.cpu_count() if not specified.
iterations: 1000

model:
  type: sdf_scene
  device: cuda:0
  
dataset:
  meshes: /dataset
  batch_size: 1
  query_size: 2048
  trajectories: 16
  bounds:
    - [-0.5, -0.8, -0.06]
    - [0.5, 0.8, 0.3]
  intrinsics:
    frame: camera
    fx: 616.36529541
    fy: 616.20294189
    cx: 310.25881958
    cy: 236.59980774
    skew: 0.0
    width: 640
    height: 480

  extrinsics:
    azimuth: [-0.2, 0.2]
    elevation: [0.6, 1.0]
    radius: [1.5, 2.0]